import chromadb
from sentence_transformers import SentenceTransformer
from ollama import chat
from pathlib import Path

BASE_DIR = Path(__file__).parent
CHROMA_PATH = BASE_DIR / "data" / "chroma_db"

class Rag():
    def __init__(self):
        self.embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
        self.chroma_client = chromadb.PersistentClient(path="data/chroma_db")
        self.collection = self.chroma_client.get_collection(name="documents")
        self.top_k = 3

    def search(self,query):                 ##two parameters: query and top_k which returns the top_k most result
        query_embedding =  self.embedding_model.encode(query)
        results = self.collection.query(
            query_embeddings = [query_embedding.tolist()],
            n_results = self.top_k
        )
        print("\nFULL RESULTS:")
        print(results)

        print("\nDOCUMENTS:")
        print(results["documents"])

    
        return results

    def generate_response(self,query,results):
        context = "\n".join(results["documents"][0])
        print("Context:", context)
        prompt = f"""
        Context: {context}
        Question: {query}
        Answer:
        """
        response = chat(model="qwen3:8b",
                        messages=[{"role": "system",
                                    "content": "Answer the question using the provided context only. If the answer is not contained within the context, say 'I don't know'."},
                                {"role": "user",
                                    "content": prompt}])

        ## returns only the content generated by the llm
        return response['message']['content']

    def ask(self,query):
        results = self.search(query)
        answer = self.generate_response(query,results)
        return answer


