import chromadb
from sentence_transformers import SentenceTransformer
from ollama import chat

embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
chroma_client = chromadb.PersistentClient(path="data/chroma_db")
collection = chroma_client.get_collection(name="documents")

def search(query,top_k=3):                 ##two parameters: query and top_k which returns the top_k most result
    query_embedding =  embedding_model.encode(query)
    results = collection.query(
        query_embeddings = [query_embedding.tolist()],
        n_results = top_k
    )
    return results

def generate_response(query,results):
    context = "\n".join(results["documents"][0])
    print("Context:", context)
    prompt = f"""
    Context: {context}
    Question: {query}
    Answer:
    """
    response = chat(model="qwen3:8b",
                    messages=[{"role": "system",
                                "content": "Answer the question using the provided context only. If the answer is not contained within the context, say 'I don't know'."},
                              {"role": "user",
                                "content": prompt}])

    ## returns only the content generated by the llm
    return response['message']['content']


if __name__ == "__main__":
    query = input("Enter your question:")
    results = search(query)          ##returns and stores the list of most relevant chunks
    answer = generate_response(query,results)
    print("Answer:", answer)
