import chromadb
from sentence_transformers import SentenceTransformer
from ollama import chat
from pathlib import Path
import config


class Rag():
    def __init__(self):
        self.embedding_model = SentenceTransformer(config.EMBEDDING_MODEL)
        self.chroma_client = chromadb.PersistentClient(path=config.CHROMA_PATH)
        self.collection = self.chroma_client.get_collection(name=config.COLLECTION_NAME)
        self.top_k = config.TOP_K

    def search(self,query):                 ##two parameters: query and top_k which returns the top_k most result
        query_embedding =  self.embedding_model.encode(query)
        results = self.collection.query(
            query_embeddings = [query_embedding.tolist()],
            n_results = self.top_k
        )
        return results

    def generate_response(self,query,results):
        context = "\n".join(results["documents"][0])
        prompt = f"""
        Context: {context}
        Question: {query}
        Answer:
        """
        response = chat(model=config.LLM_MODEL,
                        messages=[{"role": "system",
                                    "content": "Answer the question using the provided context only. If the answer is not contained within the context, say 'I don't know'."},
                                {"role": "user",
                                    "content": prompt}])

        ## returns only the content generated by the llm
        return response['message']['content']

    def ask(self,query):
        results = self.search(query)
        answer = self.generate_response(query,results)
        return answer

if __name__ == "__main__":
    rag = Rag()
    query = input("Enter your question:")
    answer = rag.ask(query)
    print("Answer:", answer)
